#ifndef X
#define X(name) name
#endif

X(AND) X(OR) X(COND) X(LOOP) X(LEQ) X(EQ) X(GEQ)
X(MOD) X(INT) X(DIGIT) X(ALPHA)
X(PLUS) X(MINUS) X(MUL) X(DIV) X(EXP)
X(NEG) X(POS)
X(LP) X(RP) X(LB) X(RB)
X(FN) X(MACRO)
X(END_OF_FILE) X(ERROR) X(UNINITIALIZED) X(EXIT) X(NUMBER) X(IDENTIFIER)
X(DEFINE)
X(LET)
X(SPACE)

#undef X